#!/usr/bin/env python3
"""Regenerate the embedded @font-face block at the foot of theme.css.

iOS has no font installer, so the theme carries its own Latin subsets of
Spectral and M PLUS 1p as base64 data URIs. Obsidian injects theme.css into a
<style> element rather than <link>ing it, so relative url() would resolve
against the app document — data URIs are the only route that works.

Run after changing FAMILIES; it rewrites everything from the FONT_FENCE marker
to the end of theme.css and leaves the rest of the file untouched.

    ./obsidian/build-fonts.py && ./obsidian/install-obsidian.sh
"""
import base64
import re
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
THEME = HERE / "theme.css"
FONT_FENCE = "/* ==========================================================================\n   Embedded webfonts"

# Google Fonts serves a different (smaller, woff2) payload to modern browsers.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# Covers all three --font-*-theme families the theme declares. Leaving one out
# means that role alone falls back to a system face on iOS, which is the exact
# failure this file exists to prevent.
CSS2 = ("https://fonts.googleapis.com/css2"
        "?family=M+PLUS+1p:wght@400;500;700"
        "&family=M+PLUS+1+Code:wght@400;700"
        "&family=Spectral:ital,wght@0,400;0,500;0,600;1,400"
        "&display=swap")

# Only the Latin subset ships. The full CJK coverage of M PLUS 1p would be
# megabytes; desktop still gets it through the local() sources below.
LATIN = "U+0000-00FF"

# family, weight, style -> local() names to try before the embedded copy, so
# machines with the Homebrew casks keep using the complete installed families.
LOCALS = {
    ("M PLUS 1p", "400", "normal"): ["M PLUS 1p", "MPLUS1p-Regular"],
    ("M PLUS 1p", "500", "normal"): ["M PLUS 1p Medium", "MPLUS1p-Medium"],
    ("M PLUS 1p", "700", "normal"): ["M PLUS 1p Bold", "MPLUS1p-Bold"],
    ("M PLUS 1 Code", "400", "normal"): ["M PLUS 1 Code", "MPLUS1Code-Regular"],
    ("M PLUS 1 Code", "700", "normal"): ["M PLUS 1 Code Bold", "MPLUS1Code-Bold"],
    ("Spectral", "400", "normal"): ["Spectral", "Spectral-Regular"],
    ("Spectral", "500", "normal"): ["Spectral Medium", "Spectral-Medium"],
    ("Spectral", "600", "normal"): ["Spectral SemiBold", "Spectral-SemiBold"],
    ("Spectral", "400", "italic"): ["Spectral Italic", "Spectral-Italic"],
}

# Metric-normalised aliases. Each source family is emitted TWICE: once stock,
# for interface chrome, and once under the alias below carrying symmetric
# ascent/descent overrides, for prose.
#
# WHY. A single-line box seats its baseline at L/2 + F*(A-D)/2, where A and D
# are the font's ascent and descent as fractions of the em and F is the font
# size. With the real metrics that second term is a per-font constant times the
# font size — Spectral 0.2980, M PLUS 1p 0.3775 — which is precisely the ladder
# of per-heading-level magic numbers this theme used to carry. Setting A = D
# makes the term vanish for EVERY font size, so every baseline sits at exactly
# L/2 and every margin becomes a plain multiple of the row.
#
# WHY ALIASES AND NOT AN OVERRIDE IN PLACE. Overriding the real Spectral would
# move its baseline up by 0.298 * font-size — about 4px at interface size —
# inside every button, menu and file-tree row, which centre their text on the
# line box. Prose gets the normalised metrics; the UI keeps the font as drawn.
#
# WHY 45%. Content-area height becomes (A + D) * F, and `line-height: 24px`
# only governs while that stays under 24px (a line box is max(strut, content)).
# The largest prose text is h1 at --h1-size 1.618em, so the ceiling is
# A <= 12 / (1.618 * baseFontSize): 0.53 at base 14, 0.46 at base 16. 45% holds
# up to roughly base 16.5. Above that h1 needs a 48px box and the half-row
# margin rule comes back.
ALIAS = {
    "M PLUS 1p": "Midori Text",
    "Spectral": "Midori Display",
    "M PLUS 1 Code": "Midori Mono",
}
ASCENT_OVERRIDE = DESCENT_OVERRIDE = "45%"
LINE_GAP_OVERRIDE = "0%"

HEADER = """/* ==========================================================================
   Embedded webfonts — Latin subsets, base64 data URIs. Generated by
   build-fonts.py; do not hand-edit below this line.

   Each family appears twice: stock, and again as a "Midori …" alias carrying
   symmetric ascent/descent overrides. The aliases are what prose uses; the
   stock copies are what the interface uses. See ALIAS in build-fonts.py for
   why the two cannot be the same face.

   WHY THIS IS HERE. Spectral and M PLUS 1p install on the Mac via Homebrew
   casks, but iOS offers no way to install a font, so on iPhone/iPad the stack
   fell through to a system serif. A different typeface seats its baseline
   elsewhere inside the same 24px line box — which is precisely what knocked
   the dot grid out of register on mobile.

   WHY DATA URIs AND NOT FILES NEXT TO theme.css. Obsidian does not <link> a
   theme; it reads theme.css and injects the text into a <style> element
   (app.js: this.styleEl.setText). Relative url() therefore resolves against
   the app document, not the theme folder, so loose .woff2 files alongside
   would silently 404. Data URIs also ride along with the single theme.css
   that install-obsidian.sh already fans out to every vault.

   local() IS LISTED FIRST on purpose: desktop keeps the full installed
   families, including the CJK coverage these Latin subsets drop.

   Source: Google Fonts (SIL Open Font License 1.1).
   ========================================================================== */"""


def fetch(url):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA})).read()


def faces():
    """Yield (family, weight, style, woff2 bytes) for the Latin subsets."""
    sheet = fetch(CSS2).decode()
    for block in re.findall(r"@font-face\s*{[^}]*}", sheet):
        get = lambda k: re.search(rf"{k}:\s*([^;]+);", block).group(1).strip()
        if LATIN not in get("unicode-range"):
            continue  # cyrillic / greek / vietnamese / CJK slices
        family = get("font-family").strip("\"'")
        url = re.search(r"url\(([^)]+)\)", block).group(1)
        yield family, get("font-weight"), get("font-style"), fetch(url)


def main():
    blocks = []
    for family, weight, style, data in sorted(faces(), key=lambda f: f[:3]):
        key = (family, weight, style)
        if key not in LOCALS:
            sys.exit(f"no local() names for {key} — add it to LOCALS")
        local = ",\n       ".join(f'local("{n}")' for n in LOCALS[key])
        b64 = base64.b64encode(data).decode()
        src = f"""  src: {local},
       url(data:font/woff2;base64,{b64}) format("woff2");"""
        blocks.append(f"""@font-face {{
  font-family: "{family}";
  font-style: {style};
  font-weight: {weight};
  font-display: swap;
{src}
}}""")
        # Metric-normalised twin. local() is kept so desktop still uses the
        # installed face; the descriptors replace its metrics either way, which
        # is also what makes this immune to the UA picking hhea over OS/2.
        blocks.append(f"""@font-face {{
  font-family: "{ALIAS[family]}";
  font-style: {style};
  font-weight: {weight};
  font-display: swap;
  ascent-override: {ASCENT_OVERRIDE};
  descent-override: {DESCENT_OVERRIDE};
  line-gap-override: {LINE_GAP_OVERRIDE};
{src}
}}""")

    if len(blocks) != 2 * len(LOCALS):
        sys.exit(f"expected {2 * len(LOCALS)} faces, got {len(blocks)}")

    css = THEME.read_text()
    head = css.split(FONT_FENCE)[0].rstrip("\n")
    THEME.write_text(head + "\n\n" + HEADER + "\n\n" + "\n\n".join(blocks) + "\n")
    print(f"embedded {len(blocks)} faces -> {THEME} ({THEME.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
